"""
# ingest_raw_files.py
This script processes raw campaign finance data files from OpenSecrets.
It saves them in Parquet.
Copyright 2025 Martin A. Valdez
"""
#%%
import duckdb
from pathlib import Path

from .integrity_qa import run_integrity_qa

# Column definitions for each file type
pacs_columns = ['Cycle', 'FECRecID', 'PACID', 'CandID', 'Amount', 'Date', 'RealCode', 'Type', 'DI', 'FECCandID']

indivs_columns = [
    'Cycle', 'FECTransID', 'ContribID', 'Contrib', 'RecipID', 'Orgname', 'UltOrg',
    'RealCode', 'Date', 'Amount', 'Street', 'City', 'State', 'Zip',
    'RecipCode', 'Type', 'CmteID', 'OtherID', 'Gender', 'Microfilm',
    'Occupation', 'Employer', 'Source'
]

cands_columns = [
    'Cycle', 'FECCandID', 'CandID', 'Name', 'Party', 'DistIDRun',
    'DistIDCurr', 'CurrCand', 'CycleCand', 'CRPICO', 'RecipCode', 'NoPacs'
]

cmtes_columns = [
    'Cycle', 'CmteID', 'PACShort', 'Affiliate', 'UltOrg', 'RecipID',
    'RecipCode', 'FECCmteID', 'Party', 'PrimCode', 'Source',
    'Sensitive', 'Foreign', 'Active'
]

# Use only the last two digits of the cycle for filenames
def get_mappings(cycle: str):
    cycle = cycle[-2:]
    return {
        f"cands{cycle}.txt":  {"output": "candidates.parquet", "columns": cands_columns},
        f"indivs{cycle}.txt": {"output": "indivs.parquet", "columns": indivs_columns},
        f"cmtes{cycle}.txt":  {"output": "committees.parquet", "columns": cmtes_columns},
        f"pacs{cycle}.txt":   {"output": "pacs.parquet", "columns": pacs_columns},
    }

# src/data/ingest_raw_files.py -> project_root = ../../
project_root = Path(__file__).resolve().parents[2]

def ingest_campaign_data(cycle: str) -> None:
    """
    Read raw OpenSecrets files for a given campaign cycle and write them out as Parquet.
    """
    mappings = get_mappings(cycle)
    cycle = cycle[-2:]

    for raw_filename, file_info in mappings.items():
        input_path = project_root / "data" / "raw" / "political" / f"CampaignFin{cycle}" / raw_filename
        output_dir = project_root / "data" / "clean" / cycle
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / file_info["output"]

        con = duckdb.connect()
        
        # First, detect the actual column names generated by DuckDB
        col_info = con.execute(f"""
            DESCRIBE (
                SELECT * FROM read_csv_auto('{input_path}',
                                           DELIM=',',
                                           QUOTE='|',
                                           HEADER=False,
                                           IGNORE_ERRORS=TRUE,
                                           ALL_VARCHAR=TRUE)
                LIMIT 1
            )
        """).fetchall()
        
        actual_col_names = [row[0] for row in col_info]
        target_cols = file_info["columns"]
        
        # Build SELECT clause with column aliasing using actual column names
        select_clauses = [f"{actual_col} AS {target_col}"
                         for actual_col, target_col in zip(actual_col_names, target_cols)]
        select_statement = ",\n                ".join(select_clauses)

        con.execute(f"""
            COPY (
              SELECT
                {select_statement}
              FROM read_csv_auto('{input_path}',
                                  DELIM=',',
                                  QUOTE='|',
                                  HEADER=False,
                                  DATEFORMAT='YYYY-MM-DD',
                                  IGNORE_ERRORS=TRUE,
                                  ALL_VARCHAR=TRUE)
            )
            TO '{output_path}'
              (FORMAT PARQUET, COMPRESSION SNAPPY);
        """)
        print(f"Processed {input_path} -> {output_path}")
#%%
if __name__ == "__main__":
    # Process all campaign cycles from 1990 to 2022 (even years only)
    cycles = [str(year) for year in range(1990, 2024, 2)]
    
    print(f"Processing {len(cycles)} campaign cycles: {', '.join(cycles)}")
    
    for cycle in cycles:
        print(f"\n--- Processing cycle {cycle} ---")
        try:
            ingest_campaign_data(cycle)
            report_path = run_integrity_qa(cycle)
            print(f"QA report: {report_path}")
            print(f"✓ Successfully processed cycle {cycle}")
        except Exception as e:
            print(f"✗ Error processing cycle {cycle}: {e}")
    
    print(f"\n--- Processing Complete ---")
    print("Generated parquet files in data/clean/ directories")
    